services:
  database:
    container_name: vending_machine_db_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vending_machine_db
    ports:
      - 5437:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: